name: Get Cookie

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  fetch-cookie:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run cookie fetcher
      run: |
        python get_cookie.py
        echo "\n✅ Contents of cookie.txt:"
        cat cookie.txt || echo "cookie.txt not found"

    - name: Commit and push cookie.txt (always)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add cookie.txt
        git commit --allow-empty -m "Update cookie.txt"
        git push origin main
